Estilo/grails-app/domain/com/librodeestilo/Libro.groovy
package com.librodeestilo

import java.util.Date;

import com.librodeestilo.auth.User

class Libro {
	String titulo
	String descripcion
	Boolean activo
	Medio medio
        Date dateCreated
        Date lastUpdated
	
	static hasMany = [propuestas: Propuesta, estilo: Propuesta, etica: Propuesta]
    
	static mapping = { descripcion type:'text' }

	static constraints = {
		titulo nullable: true
		descripcion nullable:true
		activo nullable:true
		medio nullable:true
                dateCreated nullable:true
                lastUpdated nullable:true
	}
	
	String toString(){
		return titulo
	}
}

Estilo/grails-app/domain/com/librodeestilo/Medio.groovy
package com.librodeestilo

import com.librodeestilo.auth.User

class Medio{
    String nombre
    String slug
    String url
    String descripcion
    User responsable
    Libro libro
    byte[] logo

    static mapping = {
        descripcion type:'text'
        logo sqlType:'blob', maxSize: 1000000
    }

    String toString(){
        return nombre
    }
    static constraints = { 
        nombre(nullable:true)
        slug(nullable:true)
        url(nullable:true) 
        descripcion(nullable:true)
        responsable(nullable:true)
        libro(nullable:true)
        logo(nullable:true)
    }
}

Estilo/grails-app/controllers/com/librodeestilo/MedioController.groovy
package com.librodeestilo

import com.librodeestilo.auth.User
import org.springframework.dao.DataIntegrityViolationException
import grails.plugin.springsecurity.annotation.Secured

class MedioController {

    static allowedMethods = [create: ['GET', 'POST'], edit: ['GET', 'POST'], delete: 'POST']

    def springSecurityService

    def index() {
        redirect action: 'show', params: params
    }

    @Secured(["hasRole('ROLE_ADMIN')"])
    def list() {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [medioInstanceList: Medio.list(params), medioInstanceTotal: Medio.count()]
    }

    @Secured(["hasRole('ROLE_USER')"])
    def createMedia() {
        def	user = springSecurityService.currentUser
        def libroInstance= null
        log.debug(user)

        def medio= Medio.findByResponsable(user)
        if (!medio) {
            def medioInstance = new Medio()
            medioInstance.responsable= user

            if (!medioInstance.save(flush: true)) {
                log.debug("No grabado para ${user.id}")
                flash.message = message(code: 'default.error.message', args: [
                        message(code: 'medio.label', default: 'Medio')
                    ])
                redirect controller: 'libro', action: 'master'
            }

            libroInstance = new Libro()
            libroInstance.medio= medioInstance

            if (!libroInstance.save(flush: true)) {
                log.error("No se ha creado libro para ${user.id}")
                flash.message = message(code: 'default.error.message', args: [
                        message(code: 'libro.label', default: 'Libro')
                    ])
                redirect controller: 'libro', action: 'master'
            }
            libroInstance.propuestas= Propuesta.getAll()
			
            medioInstance.libro= libroInstance
            medioInstance.save(flush:true)
        }
        else {
            libroInstance= medio.libro 
        }
        redirect controller: 'libro', action: 'edit', id: libroInstance.id		
    }

    @Secured(["hasRole('ROLE_ADMIN')"])
    def create() {
        switch (request.method) {
        case 'GET':
            [medioInstance: new Medio(params)]
            break
        case 'POST':
            def medioInstance = new Medio(params)
            medioInstance.slug= medioInstance.slug.replaceAll('[^a-z]','_')

            if (!medioInstance.save(flush: true)) {
                render view: 'create', model: [medioInstance: medioInstance]
                return
            }

            flash.message = message(code: 'default.created.message', args: [
                    message(code: 'libro.label', default: 'Medio'),
                    medioInstance.id
                ])
            redirect action: 'show', id: medioInstance.id
            break
        }
    }

    @Secured(["hasRole('ROLE_USER')"])
    def show() {
        def	user = springSecurityService.currentUser
        def medioInstance = params.id ? Medio.get(params.id) : Medio.findByResponsable(user)

        if (!medioInstance) {
            redirect action: 'create'
            return
        }

        if (medioInstance.responsable != user) {
            flash.message = message(code: 'default.not.found.message', args: [
                    message(code: 'medio.label', default: 'Medio'),
                    params.id
                ])
            redirect action: 'list'
            return
        }

        [medioInstance: medioInstance]
    }
    
    @Secured(["hasRole('ROLE_USER')"])
    def edit() {
        switch (request.method) {
        case 'GET':
            def medioInstance = Medio.get(params.id)
            if (!medioInstance) {
                flash.message = message(code: 'default.not.found.message', args: [
                        message(code: 'medio.label', default: 'Medio'),
                        params.id
                    ])
                redirect action: 'list'
                return
            }

            [medioInstance: medioInstance]
            break
        case 'POST':
            def medioInstance = Medio.get(params.id)
            if (!medioInstance) {
                flash.message = message(code: 'default.not.found.message', args: [
                        message(code: 'medio.label', default: 'Medio'),
                        params.id
                    ])
                redirect action: 'list'
                return
            }

            if (params.version) {
                def version = params.version.toLong()
                if (medioInstance.version > version) {
                    medioInstance.errors.rejectValue('version', 'default.optimistic.locking.failure',
                        [
                            message(code: 'medio.label', default: 'Medio')] as Object[],
								"Another user has updated this Medio while you were editing")
                    render view: 'edit', model: [medioInstance: medioInstance]
                    return
                }
            }

            medioInstance.properties = params
            medioInstance.slug= medioInstance.slug.replaceAll('[^a-z]','_')

            def user= springSecurityService.currentUser

            if (medioInstance.responsable != user || !medioInstance.save(flush: true)) {
                render view: 'edit', model: [medioInstance: medioInstance]
                return
            }

            flash.message = message(code: 'default.updated.message', args: [
                    message(code: 'medio.label', default: 'Medio'),
                    medioInstance.id
                ])
            redirect action: 'show', id: medioInstance.id
            break
        }
    }
  
    def test_getall() {
        //def props= Propuesta.getAll{it.epigrafe.keyword in ['firma','titulares','actualizacion','enlace']}
        def epi
        def libro= Libro.get(22)
        ['firma','titulares','actualizacion','enlace'].each{
            epi= Epigrafe.findByKeyword(it)
            libro.estilo.addAll(Propuesta.findAllByEpigrafe(epi))
        }
        [props: libro.estilo]
    }
    
    @Secured(["hasRole('ROLE_USER')"])
    def edit_1() {
        def user= springSecurityService.currentUser

        switch (request.method) {
        case 'GET':
            def medioInstance = Medio.findByResponsable(user)
            if (!medioInstance) {
                medioInstance = new Medio()
                medioInstance.responsable= user
                medioInstance.slug= user.username
                medioInstance.save()
            }

            if (!medioInstance.libro){
                def libroInstance= new Libro()
                def epi, estilo=[], etica=[]
                log.debug("Creando libro para medio: "+medioInstance.id)
                libroInstance.medio= medioInstance
                ['firma','titulares','actualizacion','enlace'].each{
                    epi= Epigrafe.findByKeyword(it)
                    estilo.addAll(Propuesta.findAllByEpigrafe(epi))
                }
                libroInstance.estilo= estilo
                ['fuentes','error','verificacion','plagio', 'redes'].each{
                    epi= Epigrafe.findByKeyword(it)
                    etica.addAll(Propuesta.findAllByEpigrafe(epi))
                }
                libroInstance.etica= etica
 
                //libroInstance.estilo= Propuesta.getAll{it.epigrafe.keyword in ['firma','titulares','actualizacion','enlace']}
                //libroInstance.etica= Propuesta.getAll{it.epigrafe.keyword in ['fuentes','error','verificacion','plagio', 'redes']}
                medioInstance.libro= libroInstance
                libroInstance.save()
                medioInstance.save()
            }
            
            [medioInstance: medioInstance]
            break
        case 'POST':
            def medioInstance = Medio.get(params.id)
            if (!medioInstance) {
                flash.message = message(code: 'default.not.found.message', args: [
                        message(code: 'medio.label', default: 'Medio'),
                        params.id
                    ])
                redirect action: 'list'
                return
            }

            if (params.version) {
                def version = params.version.toLong()
                if (medioInstance.version > version) {
                    medioInstance.errors.rejectValue('version', 'default.optimistic.locking.failure',
                        [
                            message(code: 'medio.label', default: 'Medio')] as Object[],
								"Another user has updated this Medio while you were editing")
                    render view: 'edit_1', model: [medioInstance: medioInstance]
                    return
                }
            }

            medioInstance.properties = params
            /*
            def f = request.getFile('logo')
            if (!f.empty) {
            f.transferTo(new File('/some/local/dir/myfile.txt'))
            return
            }
             */
   
            //medioInstance.slug= medioInstance.slug.replaceAll('[^a-z]','_')

            if (medioInstance.responsable != user || !medioInstance.save(flush: true)) {
                render view: 'edit_1', model: [medioInstance: medioInstance]
                return
            }

            /*
            flash.message = message(code: 'default.updated.message', args: [
            message(code: 'libro.label', default: 'Libro'),
            libroInstance.id
            ])
             */
            flash.message= "El Libro de estilo de ${medioInstance.nombre} se ha actualizado"
            
            redirect controller: 'libro', action: 'edit_2'
            break
        }
    }
        
    @Secured(["hasRole('ROLE_ADMIN')"])
    def delete() {
        def medioInstance = Medio.get(params.id)
        if (!medioInstance) {
            flash.message = message(code: 'default.not.found.message', args: [

Estilo/grails-app/views/medio/_form.gsp
<%@ page import="com.librodeestilo.Medio" %>



<div class="fieldcontain ${hasErrors(bean: medioInstance, field: 'nombre', 'error')} ">
	<label for="nombre">
		<g:message code="medio.nombre.label" default="Nombre" />
		
	</label>
	<g:textField name="nombre" value="${medioInstance?.nombre}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: medioInstance, field: 'url', 'error')} ">
	<label for="url">
		<g:message code="medio.url.label" default="Url" />
		
	</label>
	<g:textField name="url" value="${medioInstance?.url}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: medioInstance, field: 'descripcion', 'error')} ">
	<label for="descripcion">
		<g:message code="medio.descripcion.label" default="Descripcion" />
		
	</label>
	<g:textField name="descripcion" value="${medioInstance?.descripcion}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: medioInstance, field: 'responsable', 'error')} ">
	<label for="responsable">
		<g:message code="medio.responsable.label" default="Responsable" />
		
	</label>
	<g:select id="responsable" name="responsable.id" from="${com.librodeestilo.auth.User.list()}" optionKey="id" value="${medioInstance?.responsable?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

Estilo/grails-app/views/medio/create.gsp
<%@ page import="com.librodeestilo.Medio"%>
<!doctype html>
<html>
<head>
<meta name="layout" content="bootstrap">
<g:set var="entityName"
	value="${message(code: 'medio.label', default: 'Medio')}" />
<title><g:message code="default.create.label"
		args="[entityName]" /></title>
</head>
<body>
	<div class="row-fluid">

		<div class="span3">
			<div class="well">
			<sec:ifAnyGranted roles="ROLE_ADMIN">
				<ul class="nav nav-list">
					<li class="nav-header">
						${entityName}
					</li>
					<li><g:link class="list" action="list">
							<i class="icon-list"></i>
							<g:message code="default.list.label" args="[entityName]" />
						</g:link></li>
					<li class="active"><g:link class="create" action="create">
							<i class="icon-plus icon-white"></i>
							<g:message code="default.create.label" args="[entityName]" />
						</g:link></li>
				</ul>
				</sec:ifAnyGranted>
			</div>
		</div>

		<div class="span9">

			<div class="page-header">
				<h1>
					<g:message code="default.create.label" args="[entityName]" />
				</h1>
			</div>

			<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">
					${flash.message}
				</bootstrap:alert>
			</g:if>

			<g:hasErrors bean="${medioInstance}">
				<bootstrap:alert class="alert-error">
					<ul>
						<g:eachError bean="${medioInstance}" var="error">
							<li
								<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
									error="${error}" /></li>
						</g:eachError>
					</ul>
				</bootstrap:alert>
			</g:hasErrors>

			<fieldset>
				<g:form class="form-horizontal" action="create">
					<fieldset>
						<f:with bean="medioInstance">
							<f:field property="nombre" />
							<f:field property="url" />
							<f:field property="descripcion">
								<g:textArea name="${property}" value="${value}"
									class="input-block-level" style="height:300px;"></g:textArea>
							</f:field>
						</f:with>
						<div class="form-actions">
							<button type="submit" class="btn btn-primary">
								<i class="icon-ok icon-white"></i>
								<g:message code="default.button.create.label" default="Create" />
							</button>
						</div>
					</fieldset>
				</g:form>
			</fieldset>

		</div>

	</div>
</body>
</html>

Estilo/grails-app/views/medio/edit.gsp
<%@ page import="com.librodeestilo.Medio"%>
<!doctype html>
<html>
<head>
<meta name="layout" content="bootstrap">
<g:set var="entityName"
	value="${message(code: 'medio.label', default: 'Medio')}" />
<title><g:message code="default.edit.label" args="[entityName]" /></title>
<ckeditor:resources />
</head>
<body>
	<div class="row-fluid">

		<div class="span3">
			<sec:ifAnyGranted roles="ROLE_ADMIN">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">
							${entityName}
						</li>
						<li><g:link class="list" action="list">
								<i class="icon-list"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link></li>
						<li><g:link class="create" action="create">
								<i class="icon-plus"></i>
								<g:message code="default.create.label" args="[entityName]" />
							</g:link></li>
					</ul>
				</div>
			</sec:ifAnyGranted>
		</div>

		<div class="span9">

			<div class="page-header">
				<h1>Medio</h1>
			</div>

			<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">
					${flash.message}
				</bootstrap:alert>
			</g:if>

			<g:hasErrors bean="${medioInstance}">
				<bootstrap:alert class="alert-error">
					<ul>
						<g:eachError bean="${medioInstance}" var="error">
							<li
								<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
									error="${error}" /></li>
						</g:eachError>
					</ul>
				</bootstrap:alert>
			</g:hasErrors>

			<fieldset>
				<g:form class="form-horizontal" action="edit"
					id="${medioInstance?.id}">
					<g:hiddenField name="version" value="${medioInstance?.version}" />
					<fieldset>
						<f:with bean="medioInstance">
							<f:field property="nombre" />
						    <f:field property="slug"/>
							<f:field property="url" />
							<f:field property="descripcion" label="Descripción">
								<g:textArea name="${property}" value="${value}"
									class="input-block-level" style="height:300px;"></g:textArea>
							</f:field>
						</f:with>
						<g:if test="${medioInstance.libro}">
							<g:link controller="libro" action="edit"
								id="${medioInstance.libro?.id}">Editar libro</g:link>
						</g:if>
						<div class="form-actions">
							<button type="submit" class="btn btn-primary">
								<i class="icon-ok icon-white"></i>
								<g:message code="default.button.update.label" default="Update" />
							</button>
							<sec:ifAnyGranted roles="ROLE_ADMIN">
								<button type="submit" class="btn btn-danger"
									name="_action_delete" formnovalidate>
									<i class="icon-trash icon-white"></i>
									<g:message code="default.button.delete.label" default="Delete" />
								</button>
							</sec:ifAnyGranted>
						</div>
					</fieldset>
				</g:form>
			</fieldset>

		</div>

	</div>
</body>
</html>

Estilo/grails-app/views/medio/edit_1.gsp
<%@ page import="com.librodeestilo.Master"%>
<%@ page import="com.librodeestilo.Libro"%>
<!doctype html>
<html>
    <head>
        <g:set var="entityName"
        value="${message(code: 'libro.label', default: 'Libro')}" />
        <title>Libro de estilo: Ficha</title>
    </head>
    <body>
        <div class="row-fluid">

            <div class="span2">
            </div>

            <div class="span8">
                <g:if test="${flash.message}">
                    <bootstrap:alert class="alert-info">
                        ${flash.message}
                    </bootstrap:alert>
                </g:if>

                <g:hasErrors bean="${libroInstance}">
                    <bootstrap:alert class="alert-error">
                        <ul>
                            <g:eachError bean="${libroInstance}" var="error">
                                <li
                                <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                                error="${error}" /></li>
                            </g:eachError>
                        </ul>
                    </bootstrap:alert>
                </g:hasErrors>


                <div class="num">1</div>

                <h1>Ficha</h1>

                <hr/>

                <h2>Edita el nombre del medio, su dirección web, la url en librodeestilo.com y las 
                    personas que han colaborado.
                </h2>

                <g:uploadForm class="form" action="edit_1">
                <!--<g:form class="form" action="edit_1">-->
                    <g:hiddenField name="version" value="${medioInstance?.version}" />
                    <g:hiddenField name="id" value="${medioInstance?.id}" />
                    <table class="table" border="0">
                        <tr>
                            <td class="form">Nombre del medio</td>
                            <td><g:textField name="nombre" value="${medioInstance?.nombre}"/></td>
                        </tr>
                        <tr>
                            <td class="form">URL</td>
                            <td><g:textField name="url" value="${medioInstance?.url}"/></td>
                        </tr>
                        <tr>
                            <td class="form">
                                <g:if test="${medioInstance.logo && medioInstance.slug}">
                                 <img height="50" src="${createLink(controller:'libro', action:'logo')}?slug=${medioInstance.slug}" title="Logo"/>
                                 </g:if>
                                 <g:else>
                                Logo
                                 </g:else>
                                 </td>
                            <td><input type="file" name="logo"/></td>
                        </tr>
                        <tr>
                            <td class="form">URL en librodestilo.com</td>
                            <td>librodeestilo.com/<g:textField name="slug" value="${medioInstance?.slug}"/>.pdf</td>
                        </tr>
                        <tr>
                            <td class="form">Autores</td>
                            <td>
                                <g:textArea name="descripcion" value="${medioInstance?.descripcion}"
                                    class="input-block-level" style="height:300px;">
                                </g:textArea>
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>
                                <g:submitButton class="btn btn-block" name="actualizar" value="Enviar" />
                            </td>
                        </tr>
                    </table>
                <!--</g:form>-->
                </g:uploadForm>
            </div>
            <div class="span2">
            </div>
        </div>
    </body>
</html>

Estilo/grails-app/views/medio/index.gsp
<%@ page import="com.librodeestilo.Medio" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'medio.label', default: 'Medio')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-medio" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-medio" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="nombre" title="${message(code: 'medio.nombre.label', default: 'Nombre')}" />
					
						<g:sortableColumn property="url" title="${message(code: 'medio.url.label', default: 'Url')}" />
					
						<g:sortableColumn property="descripcion" title="${message(code: 'medio.descripcion.label', default: 'Descripcion')}" />
					
						<th><g:message code="medio.responsable.label" default="Responsable" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${medioInstanceList}" status="i" var="medioInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${medioInstance.id}">${fieldValue(bean: medioInstance, field: "nombre")}</g:link></td>
					
						<td>${fieldValue(bean: medioInstance, field: "url")}</td>
					
						<td>${fieldValue(bean: medioInstance, field: "descripcion")}</td>
					
						<td>${fieldValue(bean: medioInstance, field: "responsable")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${medioInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

Estilo/grails-app/views/medio/list.gsp
<%@ page import="com.librodeestilo.Medio" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'medio.label', default: 'Medio')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span3">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">${entityName}</li>
						<li class="active">
							<g:link class="list" action="list">
								<i class="icon-list icon-white"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link>
						</li>
						<li>
							<g:link class="create" action="create">
								<i class="icon-plus"></i>
								<g:message code="default.create.label" args="[entityName]" />
							</g:link>
						</li>
					</ul>
				</div>
			</div>

			<div class="span9">
				
				<div class="page-header">
					<h1><g:message code="default.list.label" args="[entityName]" /></h1>
				</div>

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>
				
				<table class="table table-striped">
					<thead>
						<tr>
						
							<g:sortableColumn property="nombre" title="${message(code: 'medio.nombre.label', default: 'Nombre')}" />
						
							<g:sortableColumn property="url" title="${message(code: 'medio.url.label', default: 'Url')}" />
						
							<g:sortableColumn property="descripcion" title="${message(code: 'medio.descripcion.label', default: 'Descripcion')}" />
						
							<th class="header"><g:message code="medio.responsable.label" default="Responsable" /></th>
						
							<th></th>
						</tr>
					</thead>
					<tbody>
					<g:each in="${medioInstanceList}" var="medioInstance">
						<tr>
						
							<td>${fieldValue(bean: medioInstance, field: "nombre")}</td>
						
							<td>${fieldValue(bean: medioInstance, field: "url")}</td>
						
							<td>${fieldValue(bean: medioInstance, field: "descripcion")}</td>
						
							<td>${fieldValue(bean: medioInstance, field: "responsable")}</td>
						
							<td class="link">
								<g:link action="show" id="${medioInstance.id}" class="btn btn-small">Show &raquo;</g:link>
							</td>
						</tr>
					</g:each>
					</tbody>
				</table>
				<div class="pagination">
					<bootstrap:paginate total="${medioInstanceTotal}" />
				</div>
			</div>

		</div>
	</body>
</html>

Estilo/grails-app/views/medio/show.gsp
<%@ page import="com.librodeestilo.Medio" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'medio.label', default: 'Medio')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span3">
			<sec:ifAnyGranted roles="ROLE_ADMIN">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">${entityName}</li>
						<li>
							<g:link class="list" action="list">
								<i class="icon-list"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link>
						</li>
						<li>
							<g:link class="create" action="create">
								<i class="icon-plus"></i>
								<g:message code="default.create.label" args="[entityName]" />
							</g:link>
						</li>
					</ul>
				</div>
				</sec:ifAnyGranted>
			</div>
			
			<div class="span9">

				<div class="page-header">
					<h1>${medioInstance?.nombre}</h1>
				</div>

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>

				<dl>				
				
									<g:if test="${medioInstance?.slug}">
						<dt><g:message code="medio.slug.label" default="Slug" /></dt>
						
							<dd><g:fieldValue bean="${medioInstance}" field="slug"/></dd>
						
					</g:if>
				
					<g:if test="${medioInstance?.url}">
						<dt><g:message code="medio.url.label" default="URL" /></dt>
						
							<dd><g:fieldValue bean="${medioInstance}" field="url"/></dd>
						
					</g:if>
				
					<g:if test="${medioInstance?.descripcion}">
						<dt><g:message code="medio.descripcion.label" default="Descripción" /></dt>
						
							<dd><g:fieldValue bean="${medioInstance}" field="descripcion"/></dd>
						
					</g:if>
				
					<g:if test="${medioInstance?.responsable}">
						<dt><g:message code="medio.responsable.label" default="Responsable" /></dt>
						
							<dd>${medioInstance?.responsable?.encodeAsHTML()}</dd>
						
					</g:if>

					<g:if test="${medioInstance?.libro}">
						<dt><g:message code="medio.libro.label" default="Libro" />
										<g:link class="btn" controller="libro" action="edit" id="${medioInstance?.libro?.id}">
						<i class="icon-pencil"></i>
						<g:message code="default.button.edit.label" default="Edit" />
							</g:link>
						</dt>
						
							<dd>
											<ul>
				<g:set var="link" value="${grailsApplication.config.grails.serverURL}"/>
				<g:set var="slug" value="${medioInstance.slug}"/>
				<li><a href="${link}/libro/${slug?:'slug'}.pdf">${link}/libro/${slug?:'slug'}.pdf</a></li>
				<li><a href="${link}/libro/${slug?:'slug'}.html">${link}/libro/${slug?:'slug'}.html</a></li>				
				</ul>

							</dd>
						
					</g:if>

				</dl>

				<g:form>
					<g:hiddenField name="id" value="${medioInstance?.id}" />
					<div class="form-actions">
						<g:link class="btn btn-primary" action="edit" id="${medioInstance?.id}">
							<i class="icon-pencil"></i>
							<g:message code="default.button.edit.label" default="Edit" />
						</g:link>
						<sec:ifAnyGranted roles="ROLE_ADMIN">
						<button class="btn btn-danger" type="submit" name="_action_delete">
							<i class="icon-trash icon-white"></i>
							<g:message code="default.button.delete.label" default="Delete" />
						</button>
						</sec:ifAnyGranted>
					</div>
				</g:form>

			</div>

		</div>
	</body>
</html>

Estilo/grails-app/views/medio/test_getall.gsp
<%@ page import="com.librodeestilo.Master"%>
<%@ page import="com.librodeestilo.Libro"%>
<!doctype html>
<html>
    <head>
        <g:set var="entityName"
        value="${message(code: 'libro.label', default: 'Libro')}" />
        <title>Libro de estilo: Ficha</title>
    </head>
    <body>

        <g:each var="p" in="${props}">
            ${p.id}
            </g:each>
    </body>
</html>