Estilo/grails-app/domain/com/librodeestilo/Epigrafe.groovy
package com.librodeestilo

import java.util.Date;

class Epigrafe implements Comparable {
	Integer orden
	String titulo
	String keyword
	String descripcion
	SortedSet propuestas

	static hasMany = [propuestas: Propuesta]
	static belongsTo = [master: Master]

	static mapping = {
		descripcion type:'text'
		propuestas(sort:'orden', order: "asc")
	}

	String toString(){
		return titulo
	}
	static constraints = { 
		orden()
		titulo(nullable:true) 
		descripcion(nullable:true) 
		}

	int compareTo(Object e){
		return orden.compareTo(e.orden)
	}
}

Estilo/grails-app/controllers/com/librodeestilo/EpigrafeController.groovy
package com.librodeestilo

import org.springframework.dao.DataIntegrityViolationException

class EpigrafeController {

    static allowedMethods = [create: ['GET', 'POST'], edit: ['GET', 'POST'], delete: 'POST']

    def index() {
        redirect action: 'list', params: params
    }

    def list() {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [epigrafeInstanceList: Epigrafe.list(params), epigrafeInstanceTotal: Epigrafe.count()]
    }

    def create() {
		switch (request.method) {
		case 'GET':
        	[epigrafeInstance: new Epigrafe(params)]
			break
		case 'POST':
	        def epigrafeInstance = new Epigrafe(params)
	        if (!epigrafeInstance.save(flush: true)) {
	            render view: 'create', model: [epigrafeInstance: epigrafeInstance]
	            return
	        }

			flash.message = message(code: 'default.created.message', args: [message(code: 'epigrafe.label', default: 'Epigrafe'), epigrafeInstance.id])
	        redirect action: 'show', id: epigrafeInstance.id
			break
		}
    }

    def show() {
        def epigrafeInstance = Epigrafe.get(params.id)
        if (!epigrafeInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'epigrafe.label', default: 'Epigrafe'), params.id])
            redirect action: 'list'
            return
        }

        [epigrafeInstance: epigrafeInstance]
    }

    def edit() {
		switch (request.method) {
		case 'GET':
	        def epigrafeInstance = Epigrafe.get(params.id)
	        if (!epigrafeInstance) {
	            flash.message = message(code: 'default.not.found.message', args: [message(code: 'epigrafe.label', default: 'Epigrafe'), params.id])
	            redirect action: 'list'
	            return
	        }

	        [epigrafeInstance: epigrafeInstance]
			break
		case 'POST':
	        def epigrafeInstance = Epigrafe.get(params.id)
	        if (!epigrafeInstance) {
	            flash.message = message(code: 'default.not.found.message', args: [message(code: 'epigrafe.label', default: 'Epigrafe'), params.id])
	            redirect action: 'list'
	            return
	        }

	        if (params.version) {
	            def version = params.version.toLong()
	            if (epigrafeInstance.version > version) {
	                epigrafeInstance.errors.rejectValue('version', 'default.optimistic.locking.failure',
	                          [message(code: 'epigrafe.label', default: 'Epigrafe')] as Object[],
	                          "Another user has updated this Epigrafe while you were editing")
	                render view: 'edit', model: [epigrafeInstance: epigrafeInstance]
	                return
	            }
	        }

	        epigrafeInstance.properties = params

	        if (!epigrafeInstance.save(flush: true)) {
	            render view: 'edit', model: [epigrafeInstance: epigrafeInstance]
	            return
	        }

			flash.message = message(code: 'default.updated.message', args: [message(code: 'epigrafe.label', default: 'Epigrafe'), epigrafeInstance.id])
	        redirect action: 'show', id: epigrafeInstance.id
			break
		}
    }

    def delete() {
        def epigrafeInstance = Epigrafe.get(params.id)
        if (!epigrafeInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'epigrafe.label', default: 'Epigrafe'), params.id])
            redirect action: 'list'
            return
        }

        try {
            epigrafeInstance.delete(flush: true)
			flash.message = message(code: 'default.deleted.message', args: [message(code: 'epigrafe.label', default: 'Epigrafe'), params.id])
            redirect action: 'list'
        }
        catch (DataIntegrityViolationException e) {
			flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'epigrafe.label', default: 'Epigrafe'), params.id])
            redirect action: 'show', id: params.id
        }
    }
}

Estilo/grails-app/views/epigrafe/_form.gsp
<%@ page import="com.librodeestilo.Epigrafe" %>



<div class="fieldcontain ${hasErrors(bean: epigrafeInstance, field: 'contenido', 'error')} ">
	<label for="contenido">
		<g:message code="epigrafe.contenido.label" default="Contenido" />
		
	</label>
	<g:textField name="contenido" value="${epigrafeInstance?.contenido}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: epigrafeInstance, field: 'master', 'error')} required">
	<label for="master">
		<g:message code="epigrafe.master.label" default="Master" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="master" name="master.id" from="${com.librodeestilo.Master.list()}" optionKey="id" required="" value="${epigrafeInstance?.master?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: epigrafeInstance, field: 'orden', 'error')} required">
	<label for="orden">
		<g:message code="epigrafe.orden.label" default="Orden" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="orden" type="number" value="${epigrafeInstance.orden}" required=""/>
</div>

<div class="fieldcontain ${hasErrors(bean: epigrafeInstance, field: 'recomendaciones', 'error')} ">
	<label for="recomendaciones">
		<g:message code="epigrafe.recomendaciones.label" default="Recomendaciones" />
		
	</label>
	<g:select name="recomendaciones" from="${com.librodeestilo.Propuesta.list()}" multiple="multiple" optionKey="id" size="5" value="${epigrafeInstance?.recomendaciones*.id}" class="many-to-many"/>
</div>

Estilo/grails-app/views/epigrafe/create.gsp
<%@ page import="com.librodeestilo.Epigrafe"%>
<!doctype html>
<html>
<head>
<meta name="layout" content="bootstrap">
<g:set var="entityName"
	value="${message(code: 'epigrafe.label', default: 'Epigrafe')}" />
<title><g:message code="default.create.label"
		args="[entityName]" /></title>
</head>
<body>
	<div class="row-fluid">

		<div class="span3">
			<div class="well">
				<ul class="nav nav-list">
					<li class="nav-header">
						${entityName}
					</li>
					<li><g:link class="list" action="list">
							<i class="icon-list"></i>
							<g:message code="default.list.label" args="[entityName]" />
						</g:link></li>
					<li class="active"><g:link class="create" action="create">
							<i class="icon-plus icon-white"></i>
							<g:message code="default.create.label" args="[entityName]" />
						</g:link></li>
				</ul>
			</div>
		</div>

		<div class="span9">

			<div class="page-header">
				<h1>
					<g:message code="default.create.label" args="[entityName]" />
				</h1>
			</div>

			<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">
					${flash.message}
				</bootstrap:alert>
			</g:if>

			<g:hasErrors bean="${epigrafeInstance}">
				<bootstrap:alert class="alert-error">
					<ul>
						<g:eachError bean="${epigrafeInstance}" var="error">
							<li
								<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
									error="${error}" /></li>
						</g:eachError>
					</ul>
				</bootstrap:alert>
			</g:hasErrors>

			<fieldset>
				<g:form class="form-horizontal" action="create">
					<fieldset>
						<f:with bean="epigrafeInstance">
						<f:field property="master" />
							<f:field property="orden" />
							<f:field property="titulo" />
							<f:field property="keyword" />
							<f:field property="descripcion">
								<g:textArea name="${property}" value="${value}"
									class="input-block-level" style="height:300px;"></g:textArea>
							</f:field>
							<f:field property="propuestas" />

						</f:with>
						<div class="form-actions">
							<button type="submit" class="btn btn-primary">
								<i class="icon-ok icon-white"></i>
								<g:message code="default.button.create.label" default="Create" />
							</button>
						</div>
					</fieldset>
				</g:form>
			</fieldset>

		</div>

	</div>
</body>
</html>

Estilo/grails-app/views/epigrafe/edit.gsp
<%@ page import="com.librodeestilo.Epigrafe"%>
<!doctype html>
<html>
<head>
<meta name="layout" content="bootstrap">
<g:set var="entityName"
	value="${message(code: 'epigrafe.label', default: 'Epigrafe')}" />
<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
	<div class="row-fluid">

		<div class="span3">
			<div class="well">
				<ul class="nav nav-list">
					<li class="nav-header">
						${entityName}
					</li>
					<li><g:link class="list" action="list">
							<i class="icon-list"></i>
							<g:message code="default.list.label" args="[entityName]" />
						</g:link></li>
					<li><g:link class="create" action="create">
							<i class="icon-plus"></i>
							<g:message code="default.create.label" args="[entityName]" />
						</g:link></li>
				</ul>
			</div>
		</div>

		<div class="span9">

			<div class="page-header">
				<h1>
					<g:message code="default.edit.label" args="[entityName]" />
				</h1>
			</div>

			<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">
					${flash.message}
				</bootstrap:alert>
			</g:if>

			<g:hasErrors bean="${epigrafeInstance}">
				<bootstrap:alert class="alert-error">
					<ul>
						<g:eachError bean="${epigrafeInstance}" var="error">
							<li
								<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
									error="${error}" /></li>
						</g:eachError>
					</ul>
				</bootstrap:alert>
			</g:hasErrors>


			<g:form class="form-horizontal" action="edit"
				id="${epigrafeInstance?.id}">
				<g:hiddenField name="version" value="${epigrafeInstance?.version}" />
				<fieldset>
					<f:with bean="epigrafeInstance">
						<f:field property="master" />
						<f:field property="orden" />
						<f:field property="titulo" />
						<f:field property="keyword" />
						<f:field property="descripcion">
							<g:textArea name="${property}" value="${value}"
								class="input-block-level" style="height:300px;"></g:textArea>
						</f:field>
						<f:field property="propuestas" />

					</f:with>
					<div class="form-actions">
						<button type="submit" class="btn btn-primary">
							<i class="icon-ok icon-white"></i>
							<g:message code="default.button.update.label" default="Update" />
						</button>
						<button type="submit" class="btn btn-danger" name="_action_delete"
							formnovalidate>
							<i class="icon-trash icon-white"></i>
							<g:message code="default.button.delete.label" default="Delete" />
						</button>
					</div>
				</fieldset>
			</g:form>

		</div>

	</div>
</body>
</html>

Estilo/grails-app/views/epigrafe/index.gsp
<%@ page import="com.librodeestilo.Epigrafe" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'epigrafe.label', default: 'Epigrafe')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-epigrafe" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-epigrafe" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="contenido" title="${message(code: 'epigrafe.contenido.label', default: 'Contenido')}" />
					
						<th><g:message code="epigrafe.master.label" default="Master" /></th>
					
						<g:sortableColumn property="orden" title="${message(code: 'epigrafe.orden.label', default: 'Orden')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${epigrafeInstanceList}" status="i" var="epigrafeInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${epigrafeInstance.id}">${fieldValue(bean: epigrafeInstance, field: "contenido")}</g:link></td>
					
						<td>${fieldValue(bean: epigrafeInstance, field: "master")}</td>
					
						<td>${fieldValue(bean: epigrafeInstance, field: "orden")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${epigrafeInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

Estilo/grails-app/views/epigrafe/list.gsp
<%@ page import="com.librodeestilo.Epigrafe" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'epigrafe.label', default: 'Epigrafe')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span3">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">${entityName}</li>
						<li class="active">
							<g:link class="list" action="list">
								<i class="icon-list icon-white"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link>
						</li>
						<li>
							<g:link class="create" action="create">
								<i class="icon-plus"></i>
								<g:message code="default.create.label" args="[entityName]" />
							</g:link>
						</li>
					</ul>
				</div>
			</div>

			<div class="span9">
				
				<div class="page-header">
					<h1><g:message code="default.list.label" args="[entityName]" /></h1>
				</div>

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>
				
				<table class="table table-striped">
					<thead>
						<tr>

							<g:sortableColumn property="orden" title="${message(code: 'epigrafe.orden.label', default: 'Orden')}" />
						
							<g:sortableColumn property="titulo" title="${message(code: 'epigrafe.contenido.label', default: 'Título')}" />
												
						
							<th></th>
						</tr>
					</thead>
					<tbody>
					<g:each in="${epigrafeInstanceList}" var="epigrafeInstance">
						<tr>
						
							<td>${fieldValue(bean: epigrafeInstance, field: "orden")}</td>
							<td>${fieldValue(bean: epigrafeInstance, field: "titulo")}</td>						
						
							<td class="link">
								<g:link action="show" id="${epigrafeInstance.id}" class="btn btn-small">Show &raquo;</g:link>
							</td>
						</tr>
					</g:each>
					</tbody>
				</table>
				<div class="pagination">
					<bootstrap:paginate total="${epigrafeInstanceTotal}" />
				</div>
			</div>

		</div>
	</body>
</html>

Estilo/grails-app/views/epigrafe/show.gsp
<%@ page import="com.librodeestilo.Epigrafe" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'epigrafe.label', default: 'Epigrafe')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span3">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">${entityName}</li>
						<li>
							<g:link class="list" action="list">
								<i class="icon-list"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link>
						</li>
						<li>
							<g:link class="create" action="create">
								<i class="icon-plus"></i>
								<g:message code="default.create.label" args="[entityName]" />
							</g:link>
						</li>
					</ul>
				</div>
			</div>
			
			<div class="span9">
				
				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>
				
				<div class="page-header">
					<h1>
					 <g:fieldValue bean="${epigrafeInstance}" field="titulo"/> </h1> 
					(<g:link controller="master" action="show" id="${epigrafeInstance?.master?.id}">${epigrafeInstance?.master?.encodeAsHTML()}</g:link>)
				</div>

<g:fieldValue bean="${epigrafeInstance}" field="orden"/>
<g:fieldValue bean="${epigrafeInstance}" field="keyword"/>

				<h2>Descripción</h2>
				<markdown:renderHtml text="${epigrafeInstance.descripcion}"/>
				
					<g:if test="${epigrafeInstance?.propuestas}">

				<h2>Propuestas</h2>


				<ol>
										
							<g:each in="${epigrafeInstance.propuestas}" var="r">
								<li>${r?.encodeAsHTML()} <g:link controller="propuesta" action="show" id="${r.id}">(ver)</g:link></dd>
							</g:each>
						
				
				</ol>
					</g:if>

				<g:form>
					<g:hiddenField name="id" value="${epigrafeInstance?.id}" />
					<div class="form-actions">
						<g:link class="btn" action="edit" id="${epigrafeInstance?.id}">
							<i class="icon-pencil"></i>
							<g:message code="default.button.edit.label" default="Edit" />
						</g:link>
						<button class="btn btn-danger" type="submit" name="_action_delete">
							<i class="icon-trash icon-white"></i>
							<g:message code="default.button.delete.label" default="Delete" />
						</button>
					</div>
				</g:form>

			</div>

		</div>
	</body>
</html>