Estilo/grails-app/domain/com/librodeestilo/Libro.groovy
package com.librodeestilo

import java.util.Date;

import com.librodeestilo.auth.User

class Libro {
	String titulo
	String descripcion
	Boolean activo
	Medio medio
        Date dateCreated
        Date lastUpdated
	
	static hasMany = [propuestas: Propuesta, estilo: Propuesta, etica: Propuesta]
    
	static mapping = { descripcion type:'text' }

	static constraints = {
		titulo nullable: true
		descripcion nullable:true
		activo nullable:true
		medio nullable:true
                dateCreated nullable:true
                lastUpdated nullable:true
	}
	
	String toString(){
		return titulo
	}
}

Estilo/grails-app/controllers/com/librodeestilo/LibroController.groovy
package com.librodeestilo

import grails.plugin.springsecurity.annotation.Secured
import com.librodeestilo.auth.User
import org.springframework.dao.DataIntegrityViolationException

class LibroController {
    static allowedMethods = [create: ['GET', 'POST'], edit: ['GET', 'POST'], delete: 'POST']

    def springSecurityService
    def wkhtmltoxService

    def index() {
        redirect action: 'html', params: params
    }

    @Secured(["hasRole('ROLE_ADMIN')"])
    def list() {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [libroInstanceList: Libro.list(params), libroInstanceTotal: Libro.count()]
    }

    @Secured(["hasRole('ROLE_ADMIN')"])
    def create() {
        def master= Master.first()
        log.debug(master)
        log.debug(params)

        switch (request.method) {
        case 'GET':
            [master: master, libroInstance: new Libro(params)]
            break
        case 'POST':

            def libroInstance = new Libro(params)
            def props= params.propuesta.keySet().findAll{it.isInteger()}
            libroInstance.propuestas= Propuesta.getAll(props)

            if (!libroInstance.save(flush: true)) {
                render view: 'create', model: [master:master, libroInstance: libroInstance]
                return
            }

            flash.message = message(code: 'default.created.message', args: [
                    message(code: 'libro.label', default: 'Libro'),
                    libroInstance.id
                ])
            redirect action: 'show', id: libroInstance.id
            break
        }
    }

    @Secured(["hasRole('ROLE_ADMIN')"])
    def show() {
        def master= Master.first()
        def libroInstance = Libro.get(params.id)
        if (!libroInstance) {
            flash.message = message(code: 'default.not.found.message', args: [
                    message(code: 'libro.label', default: 'Libro'),
                    params.id
                ])
            redirect action: 'list'
            return
        }

        [master: master, libroInstance: libroInstance]
    }
    
    def base() {
        //cache shared: true, validUntil: new Date()+1
        def master= Master.first()
        def user= params.usuario? User.findByUsername(params.usuario):null
        user= user?: springSecurityService.isLoggedIn() ? springSecurityService.loadCurrentUser() : null
        log.debug("H User: "+user?.username)
        if (!user){
            redirect controller:'info', action:'inicio'
        }

        log.debug("H Slug: "+params.slug)
        
        def medio= user ? Medio.findByResponsable(user) : params.slug ? Medio.findBySlug(params.slug) : null
        //		def libroInstance = Libro.get(params.id)
        log.debug("H Medio: "+medio?.id)
        if (!medio){
            redirect controller:'medio', action:'edit_1'
        }

        log.debug("H Libro: "+medio?.libro?.id)        
        
        def libroInstance= medio ? medio.libro : null
        
        [master: master, medio: medio, libroInstance: libroInstance]
    }
    
    def html() {
        //cache shared: true, validUntil: new Date()+1
        def master= Master.first()
        def medio= Medio.findBySlug(params.slug)
        //		def libroInstance = Libro.get(params.id)
        def libroInstance= medio ? medio.libro: master
		
        [master: master, medio: medio, libroInstance: libroInstance]
    }
   
    def logo() {
        def medio= Medio.findBySlug(params.slug)
        log.debug("Enviando logo: "+params.slug)
        response.setIntHeader('Content-length', medio.logo.length)
        response.contentType = 'image/png' // or the appropriate image content type
        if (medio && medio.logo){
            response.outputStream.write(medio.logo)
            response.outputStream.flush()
        }
    }

    def recursos() {
        //cache shared: true, validUntil: new Date()+1
        def master= Master.first()
		
        [master: master, libroInstance: master]
    }
    
    def master() {
        //cache shared: true, validUntil: new Date()+1
        def master= Master.first()

        [master: master, libroInstance: null]
    }

    def footer_view(){
    }
    
    def view_html(){
        log.debug("html_view: "+params.slug)
        if (!params.slug){
            redirect controller: 'info', action: 'inicio'
        }
        log.debug(params.format)
        def medio= Medio.findBySlug(params.slug)
        def master= Master.first()
        def libroInstance= medio?.libro
        log.debug("slug:"+medio?.slug)
 
        if (params.format=="pdf"){
            view_pdf(params)
        }
        else{
            [master: master, medio: medio, libroInstance: libroInstance]
        }
    }
        
    def view_pdf(params){
        log.debug("pdf_view: "+params.slug)
        log.debug(params.format)
        def medio= Medio.findBySlug(params.slug)
        def master= Master.first()
        def libroInstance= medio?.libro

        log.debug("Libro: "+libroInstance?.id)

        //[master: master, medio: medio, libroInstance: libroInstance]
        //ByteArrayOutputStream bytes = pdfRenderingService.render(template: "/libro/pdf", model: [master: master, libroInstance: libroInstance])
        //renderPdf([template: '/libro/pdf', model:[master: master, medio: medio, libroInstance: libroInstance], filename: "test.pdf"])

        def byte[] pdfData
        def nombre="libropdf"+(libroInstance?libroInstance.id:"0")
        log.debug(nombre)
        def cache= new File("cache").mkdirs()
        File pdf= new File("cache", nombre+".pdf")
        def checktime= new Date().minus(1).time
        
        //log.debug(libroInstance.lastUpdated?.getTime())
        //log.debug(pdf.lastModified())
        if (!pdf.exists() || pdf.lastModified()<=checktime || libroInstance.lastUpdated.getTime()>pdf.lastModified()){
            log.debug("Generando en view-pdf: "+nombre)
            def base= grailsApplication.config.grails.serverURL
            
            def cmd="/usr/local/bin/wkhtmltopdf "
            cmd= cmd+"-T 20 -L 20 -R 20 "
            
            cmd= cmd+"--footer-html "+base+"/libro/footer_view "
            //cmd= cmd+"--header-html "+base+"/libro/header_view/ "
            cmd= cmd+base+"/libro/view_html/?format=html&slug="+medio.slug+" "+pdf.getAbsolutePath()
            log.debug(cmd)
            def process= cmd.execute()
            process.waitForProcessOutput()
        }
        else{
            log.debug("Enviando desde caché")
        }

        if (pdf.isFile()){
            pdfData= pdf.bytes
                
            response.setContentType("application/pdf")
            response.setHeader("Content-disposition", "filename=\"librodeestilo.pdf\"")
            response.setContentLength(pdfData.size())

            def outputStream = null
            try {
                outputStream = response.outputStream
                outputStream << pdfData
                outputStream.flush()

            } catch (IOException e){
                log.debug('getImage() - Canceled download?', e)
            } finally {
                if (outputStream != null){
                    try {
                        outputStream.close()
                    } catch (IOException e) {
                        log.debug('Exception on close', e)
                    }
                }
            }
        }
    }
    
    def pdf() {
        def master= Master.first()
        def user= springSecurityService.isLoggedIn() ? springSecurityService.loadCurrentUser() : null
        log.debug("User: "+user?.username)
        
        log.debug("Slug: "+params.slug)
        
        def medio= user ? Medio.findByResponsable(user) : params.slug ? Medio.findBySlug(params.slug) : null
        //		def libroInstance = Libro.get(params.id)
        log.debug("Medio: "+medio?.id)
        
        def libroInstance= medio ? medio.libro : null
        
        log.debug("Libro: "+libroInstance?.id)

        //[master: master, medio: medio, libroInstance: libroInstance]
        //ByteArrayOutputStream bytes = pdfRenderingService.render(template: "/libro/pdf", model: [master: master, libroInstance: libroInstance])
        //renderPdf([template: '/libro/pdf', model:[master: master, medio: medio, libroInstance: libroInstance], filename: "test.pdf"])

        def byte[] pdfData
        def nombre="libropdf"+(libroInstance?libroInstance.id:"0")
        def cache= new File("cache").mkdirs()
        File pdf= new File("cache", nombre+".pdf")
        def checktime= new Date().minus(1).time
        
        log.debug(libroInstance.lastUpdated.getTime())
        log.debug(pdf.lastModified())
        if (true || !pdf.exists() || pdf.lastModified()<=checktime || libroInstance.lastUpdated.getTime()>pdf.lastModified()){
            log.debug("Generando "+nombre)
            pdfData = wkhtmltoxService.makePdf(
                view:"/libro/pdf",
                model:[master: master, medio: medio, libroInstance: libroInstance],
                //header:"/pdf/someHeader",
                footer:"/libro/pdffooter",
                marginLeft:20,
                marginTop:35,
                marginBottom:20,
                marginRight:20,
                headerSpacing:10
            )
            pdf.withOutputStream{
                stream -> stream <<pdfData
            }
        }
        else{
            log.debug("Enviando caché:"+pdf.getAbsolutePath())
            pdfData= pdf.bytes
        }
                
        response.setContentType("application/pdf")
        response.setHeader("Content-disposition", "filename=\"librodeestilo.pdf\"")
        response.setContentLength(pdfData.size())

        def outputStream = null
        try {
            outputStream = response.outputStream
            outputStream << pdfData
            outputStream.flush()

        } catch (IOException e){
            log.debug('getImage() - Canceled download?', e)
        } finally {

Estilo/grails-app/views/libro/_form.gsp
<%@ page import="com.librodeestilo.Libro" %>



<div class="fieldcontain ${hasErrors(bean: libroInstance, field: 'descripcion', 'error')} ">
	<label for="descripcion">
		<g:message code="libro.descripcion.label" default="Descripcion" />
		
	</label>
	<g:textField name="descripcion" value="${libroInstance?.descripcion}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: libroInstance, field: 'recomendaciones', 'error')} ">
	<label for="recomendaciones">
		<g:message code="libro.recomendaciones.label" default="Recomendaciones" />
		
	</label>
	<g:select name="recomendaciones" from="${com.librodeestilo.Propuesta.list()}" multiple="multiple" optionKey="id" size="5" value="${libroInstance?.recomendaciones*.id}" class="many-to-many"/>
</div>

Estilo/grails-app/views/libro/_pdf_bare.gsp
<%@ page import="com.librodeestilo.Master"%>
<%@ page import="com.librodeestilo.Libro"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<meta name="layout" content="bootstrap" />
<g:set var="entityName"
	value="${message(code: 'libro.label', default: 'Libro de estilo')}" />
<title>Libro de estilo</title>
<style type="text/css">
@page {
	size: 210mm 297mm;
}
li {
    page-break-inside: avoid;
  }
</style>
</head>
<body>
	<div class="row-fluid">

		<div class="span1"></div>

		<div class="span10">

			<div style="page-break-after: always;">

				<g:if test="${medio}">
					<h2>
						${medio.nombre}
					</h2>
					${medio.descripcion}
				</g:if>
				<g:else>
					<h2>Libro de estilo</h2>
					<markdown:renderHtml text="${master.descripcion}" />
				</g:else>
			</div>

			<g:each status="i" in="${master.epigrafes}" var="e">
				<g:if test="${e.propuestas}">

					<div class="epigrafe">
					
					<div style="page-break-inside: avoid;">
						<h2>
							${e.titulo}
						</h2>

						
						<markdown:renderHtml text="${e.descripcion}" />
					</div>
						<ul>
							<g:if test="${libroInstance}">
								<g:each
									in="${libroInstance.propuestas.findAll{it.epigrafe==e}.sort()}"
									var="r">
									<li><markdown:renderHtml text="${r.contenido}" /></li>
								</g:each>
							</g:if>
							<g:else>
								<g:each status="j" in="${e.propuestas.sort()}" var="r">
									<li><markdown:renderHtml text="${r.contenido}" /></li>

								</g:each>
							</g:else>
						</ul>
					</div>
				</g:if>
			</g:each>

		</div>
	</div>
</body>
</html>

Estilo/grails-app/views/libro/base.gsp
<%@ page import="com.librodeestilo.Master"%>
<%@ page import="com.librodeestilo.Libro"%>
<%@ page import="com.librodeestilo.Epigrafe"%>
<!doctype html>
<html>
    <head>
        <g:set var="entityName"
        value="${message(code: 'libro.label', default: 'Libro de estilo')}" />
        <title>Libro de estilo</title>
    </head>
    <body>
        
        <div class="row-fluid">
            <div class="span2"></div>
            <div class="span8">

                <g:if test="${libroInstance}">
                    <h1>Hola, <sec:loggedInUserInfo field="username"/></h1>
                    <h2>
                        Este es tu libro de estilo. Pincha en 'Editar' para editar su contenido o accede a la versión web (html) y 
                        descargable (pdf).
                    </h2>                
                <div>
                    <div class="row">
                        <div class="span4">
                        <img src="${resource(dir: 'images', file: 'lde-triptico.png')}" alt="Libro de estilo"/>
                    </div>
                    <div class="span8" style="margin:auto">
                    <ul class="opciones">
                        <g:set var="link" value="${grailsApplication.config.grails.serverURL}"/>
                        <g:set var="slug" value="${libroInstance.medio.slug}"/>
                        <g:set var="nombre" value="${libroInstance.medio.nombre}"/>
                        <g:set var="modificacion" value="${libroInstance.lastUpdated}"/>
                        <h3>${nombre}</h3>
                        <g:if test="${modificacion}">
                            <h4><g:formatDate format="dd 'de' MMMMM 'de' yyyy"date="${libroInstance?.lastUpdated}" style="LONG"/></h4>
                        </g:if>
                        <li><g:link controller="medio" action="edit_1">EDITAR</g:link> |</li>
                        <li> <g:link controller="libro" action="view_html" params="[slug:slug, format:'pdf']">PDF</g:link> |</li>
                        <li> <g:link controller="libro" action="view_html" params="[slug:slug, format: 'html']">HTML</g:link></li>				
                        <!--
                        <li> <g:link controller="libro" action="view_pdf" params="[slug:slug]">PDF</g:link> |</li>
                        <li> <g:link controller="libro" action="view_html" params="[slug:slug]">HTML</g:link></li>
                        -->
                        </ul>
                    </div>
                    </div>
                </div>

                </g:if>
                <g:else>
                    <h2>
                        ¿Listo para empezar? Te hemos preparado un borrador de libro de estilo  con una serie de propuestas por defecto.
                        <g:link controller="medio" action="edit_1"> Entra, edita y publica.</g:link>
                    </h2>
                </g:else>   
            </div>
            <div class="span2">

            </div>

        </div>
    </body>
</html>

Estilo/grails-app/views/libro/create.gsp
<%@ page import="com.librodeestilo.Master"%>
<%@ page import="com.librodeestilo.Libro"%>

<!doctype html>
<html>
<head>
<meta name="layout" content="bootstrap">
<g:set var="entityName"
	value="${message(code: 'libro.label', default: 'Libro')}" />
<title><g:message code="default.create.label"
		args="[entityName]" /></title>
</head>
<body>

	<div class="row-fluid">

		<div class="span3">
			<div class="well">
			<sec:ifAnyGranted roles="ROLE_ADMIN">
				<ul class="nav nav-list">
					<li class="nav-header">
						${entityName}
					</li>
					<li><g:link class="list" action="list">
							<i class="icon-list"></i>
							<g:message code="default.list.label" args="[entityName]" />
						</g:link></li>
					<li class="active"><g:link class="create" action="create">
							<i class="icon-plus icon-white"></i>
							<g:message code="default.create.label" args="[entityName]" />
						</g:link></li>
				</ul>
				</sec:ifAnyGranted>
			</div>
		</div>

		<div class="span9">

			<div class="page-header">
				<h1>
					<g:message code="default.create.label" args="[entityName]" />
				</h1>
			</div>

			<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">
					${flash.message}
				</bootstrap:alert>
			</g:if>

			<g:hasErrors bean="${libroInstance}">
				<bootstrap:alert class="alert-error">
					<ul>
						<g:eachError bean="${libroInstance}" var="error">
							<li
								<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
									error="${error}" /></li>
						</g:eachError>
					</ul>
				</bootstrap:alert>
			</g:hasErrors>


			<g:form class="form-horizontal" action="create">
				<fieldset>
					<f:field bean="libroInstance" property="titulo" />
					<f:field bean="libroInstance"property="descripcion">
					<g:textArea name="${property}" value="${value}" class="input-block-level" style="height:300px;"></g:textArea>
					</f:field>

					<div class="bs-example bs-example-tabs">
						<ul id="myTab" class="nav nav-tabs">
							<g:each status="i" in="${master.epigrafes}" var="e">
								<li ${i==0?'class="active"':''}><a
									href="#${e.keyword}" data-toggle="tab"> ${e.titulo}
								</a></li>
							</g:each>
						</ul>
						<div id="myTabContent" class="tab-content">
							<g:each status="i" in="${master.epigrafes}" var="e">

								<div class="tab-pane fade in ${i==0?'active':''}"
									id="${e.keyword}">
									<ul>

										<g:each in="${e.propuestas.sort()}" var="r">
											<li><g:checkBox name="propuesta.${r.id}"
													value="${libroInstance.propuestas?.contains(r)}" /> <markdown:renderHtml
													text="${r.contenido}" /></li>
										</g:each>
									</ul>
								</div>
							</g:each>
						</div>
					</div>


					<div class="form-actions">
						<button type="submit" class="btn btn-primary">
							<i class="icon-ok icon-white"></i>
							<g:message code="default.button.create.label" default="Create" />
						</button>
					</div>
				</fieldset>
			</g:form>


		</div>

	</div>
</body>
</html>

Estilo/grails-app/views/libro/edit_2.gsp
<%@ page import="com.librodeestilo.Master"%>
<%@ page import="com.librodeestilo.Libro"%>
<!doctype html>
<html>
    <head>
        <g:set var="entityName"
        value="${message(code: 'libro.label', default: 'Libro')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="row-fluid">

            <div class="span2">
            </div>

            <div class="span8">

                <g:if test="${flash.message}">
                    <bootstrap:alert class="alert-info">
                        ${flash.message}
                    </bootstrap:alert>
                </g:if>

                <g:hasErrors bean="${libroInstance}">
                    <bootstrap:alert class="alert-error">
                        <ul>
                            <g:eachError bean="${libroInstance}" var="error">
                                <li
                                <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                                    error="${error}" /></li>
                            </g:eachError>
                        </ul>
                    </bootstrap:alert>
                </g:hasErrors>

                
                 <div class="num">2</div>

                <h1>Introducción</h1>

                <hr/>

                <h2>Este el texto que presenta el libro de estilo del medio a los lectores y expone 
                    la motivación del mismo.</h2>

                <g:form class="form" action="edit_2"
                id="${libroInstance?.id}">
                    <g:hiddenField name="version" value="${libroInstance?.version}" />

                                <g:textArea name="descripcion" value="${libroInstance.descripcion}"
                                    class="input-block-level" style="height:300px;">
                                </g:textArea>
                   
                                <g:submitButton class="btn btn-block" name="actualizar" value="Enviar" />

            </g:form>

        </div>

    </div>
</body>
</html>

Estilo/grails-app/views/libro/edit_4.gsp
<%@ page import="com.librodeestilo.Master"%>
<%@ page import="com.librodeestilo.Libro"%>
<%@ page import="com.librodeestilo.Epigrafe"%>

<!doctype html>
<html>
    <head>
        <g:set var="entityName"
        value="${message(code: 'libro.label', default: 'Libro')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="row-fluid">

            <div class="span2">
            </div>

            <div class="span8">

                <g:if test="${flash.message}">
                    <bootstrap:alert class="alert-info">
                        ${flash.message}
                    </bootstrap:alert>
                </g:if>

                <g:hasErrors bean="${libroInstance}">
                    <bootstrap:alert class="alert-error">
                        <ul>
                            <g:eachError bean="${libroInstance}" var="error">
                                <li
                                <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                                error="${error}" /></li>
                            </g:eachError>
                        </ul>
                    </bootstrap:alert>
                </g:hasErrors>

                <div class="num">4</div>

                <h1>Ética</h1>

                <hr/>

                <h2>En cada sección hay una serie de epígrafes y propuestas para configurar tu libro de estilo. Por defecto aparecen todas seleccionadas. Deselecciona las que no te interesen y añade las que consideres oportunas. Aquí se incluyen las normas relacionadas con la ética periodística</h2>
                
                <g:form action="edit_4" id="${libroInstance?.id}">
                    <g:hiddenField name="version" value="${libroInstance?.version}" />
                                   
                        <g:each status="i" in="${['fuentes','error','verificacion','plagio', 'redes']}" var="k">
                            <g:set var="e" value="${Epigrafe.findByKeyword(k)}"/>
                                <div class="epi-neg">${e.titulo}</div>
                                    <p>${e.descripcion}</p>
                                <div class="epi-neg">Propuestas</div>
                                    <ul class="propuestas">
                                        <g:each in="${e.propuestas.sort()}" var="r">
                                            <li><g:checkBox name="propuesta.${r.id}"
                                                value="${libroInstance.etica?.contains(r)}" /> ${r.contenido}</li>
                                        </g:each>
                                    </ul>
                               
                        </g:each>
                    
                                <g:submitButton class="btn btn-block" name="actualizar" value="Enviar" />

            </g:form>

        </div>
        <div class="span2">
        </div>

    </div>
</body>
</html>

Estilo/grails-app/views/libro/footer_view.gsp
<!--
  To change this license header, choose License Headers in Project Properties.
  To change this template file, choose Tools | Templates
  and open the template in the editor.
-->

<%@ page contentType="text/html;charset=UTF-8" %>

<html>
    <head>
        <meta name="layout" content="lde-pdf">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Sample title</title>
    </head>
    <body style="border:0; margin: 0;">
            <img class="centered" src="${resource(dir: 'images', file: 'lde-gris-100x94.png')}" alt="Libro de estilo"/>
            <div class="lde-powered">
                En colaboración con
            </div>
            <div class="lde-powered-neg">
                www.librodeestilo.com
            </div>
    </body>
</html>

Estilo/grails-app/views/libro/header_view.gsp
<!--
  To change this license header, choose License Headers in Project Properties.
  To change this template file, choose Tools | Templates
  and open the template in the editor.
-->

<%@ page contentType="text/html;charset=UTF-8" %>

<html>
    <head>
        <meta name="layout" content="lde-pdf">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Sample title</title>
    </head>
    <body>
        <div style="margin:auto">
            <img class="centered" src="${resource(dir: 'images', file: 'lde-gris-100x94.png')}" alt="Libro de estilo"/>
            <div class="lde-powered">
                En colaboración con
            </div>
            <div class="lde-powered-neg">
                www.librodeestilo.com
            </div>

        </div>
    </body>
</html>

Estilo/grails-app/views/libro/index.gsp
<%@ page import="com.librodeestilo.Libro" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'libro.label', default: 'Libro')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-libro" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-libro" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="descripcion" title="${message(code: 'libro.descripcion.label', default: 'Descripcion')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${libroInstanceList}" status="i" var="libroInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${libroInstance.id}">${fieldValue(bean: libroInstance, field: "descripcion")}</g:link></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${libroInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

Estilo/grails-app/views/libro/list.gsp
<%@ page import="com.librodeestilo.Libro" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'libro.label', default: 'Libro')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span3">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">${entityName}</li>
						<li class="active">
							<g:link class="list" action="list">
								<i class="icon-list icon-white"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link>
						</li>
						<li>
							<g:link class="create" action="create">
								<i class="icon-plus"></i>
								<g:message code="default.create.label" args="[entityName]" />
							</g:link>
						</li>
					</ul>
				</div>
			</div>

			<div class="span9">
				
				<div class="page-header">
					<h1><g:message code="default.list.label" args="[entityName]" /></h1>
				</div>

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>
				
				<table class="table table-striped">
					<thead>
						<tr>
						
							<g:sortableColumn property="descripcion" title="${message(code: 'libro.descripcion.label', default: 'Descripcion')}" />
						
							<th></th>
						</tr>
					</thead>
					<tbody>
					<g:each in="${libroInstanceList}" var="libroInstance">
						<tr>
						
							<td>${fieldValue(bean: libroInstance, field: "descripcion")}</td>
						
							<td class="link">
								<g:link action="show" id="${libroInstance.id}" class="btn btn-small">Show &raquo;</g:link>
							</td>
						</tr>
					</g:each>
					</tbody>
				</table>
				<div class="pagination">
					<bootstrap:paginate total="${libroInstanceTotal}" />
				</div>
			</div>

		</div>
	</body>
</html>

Estilo/grails-app/views/libro/pdffooter.gsp
<!--
  To change this license header, choose License Headers in Project Properties.
  To change this template file, choose Tools | Templates
  and open the template in the editor.
-->

<%@ page contentType="text/html;charset=UTF-8" %>

<html>
    <head>
        <meta name="layout" content="lde-pdf">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Sample title</title>
    </head>
    <body>
        no images
      <img src="/Estilo/static/images/lde-triptico.png" alt="Libro de estilo"/>

    </body>
</html>