Estilo/grails-app/domain/com/librodeestilo/Info.groovy
package com.librodeestilo

class Info implements Comparable {
	String orden
	String titulo
	String descripcion

	static mapping = { descripcion type:'text' }

	static constraints = {
		titulo nullable: true
		descripcion nullable:true
	}
	
	String toString(){
		return titulo
	}
	
	int compareTo(Object e){
		return orden.compareTo(e.orden)
	}
}

Estilo/grails-app/controllers/com/librodeestilo/InfoController.groovy
package com.librodeestilo

import org.springframework.dao.DataIntegrityViolationException
import grails.plugin.springsecurity.annotation.Secured


class InfoController {

    static allowedMethods = [create: ['GET', 'POST'], edit: ['GET', 'POST'], delete: 'POST']

    @Secured(["hasRole('ROLE_ADMIN')"])
    def index() {
        redirect action: 'list', params: params
    }
	
    @Secured(["hasRole('ROLE_ADMIN')"])
    def list() {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [infoInstanceList: Info.list(params), infoInstanceTotal: Info.count()]
    }

    @Secured(["hasRole('ROLE_ADMIN')"])
    def create() {
        switch (request.method) {
        case 'GET':
            [infoInstance: new Info(params)]
            break
        case 'POST':
            def infoInstance = new Info(params)
            if (!infoInstance.save(flush: true)) {
                render view: 'create', model: [infoInstance: infoInstance]
                return
            }

            flash.message = message(code: 'default.created.message', args: [message(code: 'info.label', default: 'Info'), infoInstance.id])
            redirect action: 'show', id: infoInstance.id
            break
        }
    }

    @Secured(["hasRole('ROLE_ADMIN')"])
    def show() {
        def infoInstance = Info.get(params.id)
        if (!infoInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'info.label', default: 'Info'), params.id])
            redirect action: 'list'
            return
        }

        [infoInstance: infoInstance]
    }

    def v(Integer id) {
        def infoInstance = Info.get(id)
        if (!infoInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'info.label', default: 'Info'), params.id])
            redirect action: 'list'
            return
        }

        [infoInstance: infoInstance]
    }
    
    def acerca_de() {
    }
    
    def inicio() {
    }
	
    @Secured(["hasRole('ROLE_ADMIN')"])
    def edit() {
        switch (request.method) {
        case 'GET':
            def infoInstance = Info.get(params.id)
            if (!infoInstance) {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'info.label', default: 'Info'), params.id])
                redirect action: 'list'
                return
            }

            [infoInstance: infoInstance]
            break
        case 'POST':
            def infoInstance = Info.get(params.id)
            if (!infoInstance) {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'info.label', default: 'Info'), params.id])
                redirect action: 'list'
                return
            }

            if (params.version) {
                def version = params.version.toLong()
                if (infoInstance.version > version) {
                    infoInstance.errors.rejectValue('version', 'default.optimistic.locking.failure',
                        [message(code: 'info.label', default: 'Info')] as Object[],
	                          "Another user has updated this Info while you were editing")
                    render view: 'edit', model: [infoInstance: infoInstance]
                    return
                }
            }

            infoInstance.properties = params

            if (!infoInstance.save(flush: true)) {
                render view: 'edit', model: [infoInstance: infoInstance]
                return
            }

            flash.message = message(code: 'default.updated.message', args: [message(code: 'info.label', default: 'Info'), infoInstance.id])
            redirect action: 'show', id: infoInstance.id
            break
        }
    }

    @Secured(["hasRole('ROLE_ADMIN')"])
    def delete() {
        def infoInstance = Info.get(params.id)
        if (!infoInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'info.label', default: 'Info'), params.id])
            redirect action: 'list'
            return
        }

        try {
            infoInstance.delete(flush: true)
            flash.message = message(code: 'default.deleted.message', args: [message(code: 'info.label', default: 'Info'), params.id])
            redirect action: 'list'
        }
        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'info.label', default: 'Info'), params.id])
            redirect action: 'show', id: params.id
        }
    }
}

Estilo/grails-app/views/info/_form.gsp
<%@ page import="com.librodeestilo.Info" %>



<div class="fieldcontain ${hasErrors(bean: infoInstance, field: 'titulo', 'error')} ">
	<label for="titulo">
		<g:message code="info.titulo.label" default="Titulo" />
		
	</label>
	<g:textField name="titulo" value="${infoInstance?.titulo}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: infoInstance, field: 'descripcion', 'error')} ">
	<label for="descripcion">
		<g:message code="info.descripcion.label" default="Descripcion" />
		
	</label>
	<g:textField name="descripcion" value="${infoInstance?.descripcion}"/>
</div>

Estilo/grails-app/views/info/acerca_de.gsp
<%@ page import="com.librodeestilo.Info" %>
<!doctype html>
<html>
    <head>
        <meta name="layout" content="lde">
        <g:set var="entityName" value="${message(code: 'info.label', default: 'Info')}" />
        <title>Acerca de librodeestilo.com</title>
    </head>
    <body>
        <div class="row-fluid">

            <div class="span2">
            </div>

            <div class="span8">
                <div class="headline">
                <h1>Acerca de librodeestilo.com</h1>
                </div>
                
                <h2>
                    Un proyecto de la Universidad del País Vasco / Euskal Herriko Unibertsitatea  creado por y para periodistas
                </h2>

                <p class="first">
                    El presente libro de estilo tiene una doble función: ser una herramienta y ser un contrato. 
                    La herramienta no es otra que el <strong>método periodístico</strong> de obtención y expresión de la información, puesto a disposición de todas aquellas personas 
                    (Quién) que desean informar sobre cualquier tema (Qué), en cualquier momento 
                    (Cuándo), desde cualquier lugar y medio (Dónde), por cualquier razón (Por qué).
                </p>
                <p>
                    Sirviéndonos del esquema narrativo de la Pirámide Invertida, base expresiva de la 
                    práctica periodística, este libro de estilo se ocupa de la pregunta Cómo, cuál es el 
                    método para elaborar una información.
                </p>
                <p>
                    Por otro lado, es un <strong>contrato</strong> en el que el medio elige libre y voluntariamente 
                    la parte del método que va a cumplir, esto es, qué límites va a tener su práctica 
                    informativa, y los hace públicos, de forma que su audiencia es conocedora de 
                    dicha práctica y puede exigir (solo) en consecuencia.
                </p>
                <p>  
                    El libro de estilo tiene una <strong>estructura</strong> triangular y dinámica. Es triangular 
                    porque se asienta en tres ejes: las propuestas que tratan de sintetizar el método; 
                    la participación abierta a todos los usuarios en relación para completar dicho 
                    método; y las preguntas y respuestas que surgen sobre el mismo, y que generan 
                    una reflexión. Y es una estructura dinámica porque los tres ejes se relacionan 
                    entre sí de manera constante y biunívoca, y porque es un proyecto que tiene la 
                    vocación de responder a las necesidades del momento. Que está en progresión 
                    constante, abierto...
                </p>
                <p>
                    El <strong>equipo</strong> de trabajo que ha puesto en marcha este libro de estilo participa de 
                    esta estructura triangular y dinámica. Está formado por un grupo de periodistas 
                    en activo, con una larga trayectoria profesional, y un grupo de profesores de la 
                    Universidad del País Vasco UPV/EHU. A ambos grupos se suma un tercero, el 
                    conjunto de usuarios que, a través de su participación, completará el libro de 
                    estilo.
                </p>
            </div>
            <div class="span2"></div>

        </div>
    </div>
</body>
</html>

Estilo/grails-app/views/info/create.gsp
<%@ page import="com.librodeestilo.Info" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'info.label', default: 'Info')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span3">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">${entityName}</li>
						<li>
							<g:link class="list" action="list">
								<i class="icon-list"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link>
						</li>
						<li class="active">
							<g:link class="create" action="create">
								<i class="icon-plus icon-white"></i>
								<g:message code="default.create.label" args="[entityName]" />
							</g:link>
						</li>
					</ul>
				</div>
			</div>
			
			<div class="span9">

				<div class="page-header">
					<h1><g:message code="default.create.label" args="[entityName]" /></h1>
				</div>

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>

				<g:hasErrors bean="${infoInstance}">
				<bootstrap:alert class="alert-error">
				<ul>
					<g:eachError bean="${infoInstance}" var="error">
					<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
					</g:eachError>
				</ul>
				</bootstrap:alert>
				</g:hasErrors>

				<fieldset>
					<g:form class="form-horizontal" action="create" >
						<fieldset>
						<f:with bean="infoInstance">
							<f:field property="orden" />
							<f:field property="titulo" />
							<f:field property="descripcion">
								<g:textArea name="${property}" value="${value}"
									class="input-block-level" style="height:300px;"></g:textArea>

							</f:field>
						</f:with>
							<div class="form-actions">
								<button type="submit" class="btn btn-primary">
									<i class="icon-ok icon-white"></i>
									<g:message code="default.button.create.label" default="Create" />
								</button>
							</div>
						</fieldset>
					</g:form>
				</fieldset>
				
			</div>

		</div>
	</body>
</html>

Estilo/grails-app/views/info/edit.gsp
<%@ page import="com.librodeestilo.Info"%>
<!doctype html>
<html>
<head>
<meta name="layout" content="bootstrap">
<g:set var="entityName"
	value="${message(code: 'info.label', default: 'Info')}" />
<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
	<div class="row-fluid">

		<div class="span3">
			<div class="well">
				<ul class="nav nav-list">
					<li class="nav-header">
						${entityName}
					</li>
					<li><g:link class="list" action="list">
							<i class="icon-list"></i>
							<g:message code="default.list.label" args="[entityName]" />
						</g:link></li>
					<li><g:link class="create" action="create">
							<i class="icon-plus"></i>
							<g:message code="default.create.label" args="[entityName]" />
						</g:link></li>
				</ul>
			</div>
		</div>

		<div class="span9">

			<div class="page-header">
				<h1>
					<g:message code="default.edit.label" args="[entityName]" />
				</h1>
			</div>

			<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">
					${flash.message}
				</bootstrap:alert>
			</g:if>

			<g:hasErrors bean="${infoInstance}">
				<bootstrap:alert class="alert-error">
					<ul>
						<g:eachError bean="${infoInstance}" var="error">
							<li
								<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
									error="${error}" /></li>
						</g:eachError>
					</ul>
				</bootstrap:alert>
			</g:hasErrors>

			<fieldset>
				<g:form class="form-horizontal" action="edit"
					id="${infoInstance?.id}">
					<g:hiddenField name="version" value="${infoInstance?.version}" />
					<fieldset>
						<f:with bean="infoInstance">
							<f:field property="orden" />
							<f:field property="titulo" />
							<f:field property="descripcion">
								<g:textArea name="${property}" value="${value}"
									class="input-block-level" style="height:300px;"></g:textArea>

							</f:field>
						</f:with>
						<div class="form-actions">
							<button type="submit" class="btn btn-primary">
								<i class="icon-ok icon-white"></i>
								<g:message code="default.button.update.label" default="Update" />
							</button>
							<button type="submit" class="btn btn-danger"
								name="_action_delete" formnovalidate>
								<i class="icon-trash icon-white"></i>
								<g:message code="default.button.delete.label" default="Delete" />
							</button>
						</div>
					</fieldset>
				</g:form>
			</fieldset>

		</div>

	</div>
</body>
</html>

Estilo/grails-app/views/info/index.gsp
<%@ page import="com.librodeestilo.Info" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'info.label', default: 'Info')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-info" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-info" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="titulo" title="${message(code: 'info.titulo.label', default: 'Titulo')}" />
					
						<g:sortableColumn property="descripcion" title="${message(code: 'info.descripcion.label', default: 'Descripcion')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${infoInstanceList}" status="i" var="infoInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${infoInstance.id}">${fieldValue(bean: infoInstance, field: "titulo")}</g:link></td>
					
						<td>${fieldValue(bean: infoInstance, field: "descripcion")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${infoInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

Estilo/grails-app/views/info/inicio.gsp
<%@ page import="com.librodeestilo.Info" %>
<!doctype html>
<html>
    <head>
        <meta name="layout" content="lde">
        <g:set var="entityName" value="${message(code: 'info.label', default: 'Info')}" />
        <title>${infoInstance?.titulo}</title>
    </head>
    <body>
        <div class="row-fluid">

            <div class="span2">

            </div>

            <div class="span8">
                <div class="cab">Libro de estilo</div>

                <h2>Una herramienta colaborativa para medios de comunicación...</h2>

                <p>
      ...creada por periodistas, profesores de la UPV/EHU y técnicos para generar un libro de estilo periodístico a medida partiendo de los recursos existentes. <a href="/info/acerca_de/">Más información</a>.
                </p>
            </div>
            
            <div class="span2">

            </div>

        </div>
    </div>
</body>
</html>

Estilo/grails-app/views/info/list.gsp
<%@ page import="com.librodeestilo.Info" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'info.label', default: 'Info')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span3">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">${entityName}</li>
						<li class="active">
							<g:link class="list" action="list">
								<i class="icon-list icon-white"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link>
						</li>
						<li>
							<g:link class="create" action="create">
								<i class="icon-plus"></i>
								<g:message code="default.create.label" args="[entityName]" />
							</g:link>
						</li>
					</ul>
				</div>
			</div>

			<div class="span9">
				
				<div class="page-header">
					<h1><g:message code="default.list.label" args="[entityName]" /></h1>
				</div>

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>
				
				<table class="table table-striped">
					<thead>
						<tr>
						
							<g:sortableColumn property="titulo" title="${message(code: 'info.titulo.label', default: 'Titulo')}" />
						
							<g:sortableColumn property="descripcion" title="${message(code: 'info.descripcion.label', default: 'Descripcion')}" />
						
							<th></th>
						</tr>
					</thead>
					<tbody>
					<g:each in="${infoInstanceList}" var="infoInstance">
						<tr>
						
							<td>${fieldValue(bean: infoInstance, field: "titulo")}</td>
						
							<td>${fieldValue(bean: infoInstance, field: "descripcion")}</td>
						
							<td class="link">
								<g:link action="show" id="${infoInstance.id}" class="btn btn-small">Show &raquo;</g:link>
							</td>
						</tr>
					</g:each>
					</tbody>
				</table>
				<div class="pagination">
					<bootstrap:paginate total="${infoInstanceTotal}" />
				</div>
			</div>

		</div>
	</body>
</html>

Estilo/grails-app/views/info/show.gsp
<%@ page import="com.librodeestilo.Info" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'info.label', default: 'Info')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span3">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">${entityName}</li>
						<li>
							<g:link class="list" action="list">
								<i class="icon-list"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link>
						</li>
						<li>
							<g:link class="create" action="create">
								<i class="icon-plus"></i>
								<g:message code="default.create.label" args="[entityName]" />
							</g:link>
						</li>
					</ul>
				</div>
			</div>
			
			<div class="span9">

				<div class="page-header">
					<h1><g:message code="default.show.label" args="[entityName]" /></h1>
				</div>

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>

				<dl>
				
					<g:if test="${infoInstance?.titulo}">
						
							<h2><g:fieldValue bean="${infoInstance}" field="titulo"/></h2>
						
					</g:if>
				
					<g:if test="${infoInstance?.descripcion}">
							<markdown:renderHtml text="${infoInstance.descripcion}" />						
					</g:if>
				
				</dl>


				<sec:ifAnyGranted roles="ROLE_ADMIN">
				<g:form>
					<g:hiddenField name="id" value="${infoInstance?.id}" />
					<div class="form-actions">
						<g:link class="btn" action="edit" id="${infoInstance?.id}">
							<i class="icon-pencil"></i>
							<g:message code="default.button.edit.label" default="Edit" />
						</g:link>
						<button class="btn btn-danger" type="submit" name="_action_delete">
							<i class="icon-trash icon-white"></i>
							<g:message code="default.button.delete.label" default="Delete" />
						</button>
					</div>
				</g:form>
				</sec:ifAnyGranted>

			</div>

		</div>
	</body>
</html>

Estilo/grails-app/views/info/v.gsp
<%@ page import="com.librodeestilo.Info" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'info.label', default: 'Info')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span3">
	
			</div>
			
			<div class="span9">

				<div class="page-header">
<g:if test="${infoInstance?.titulo}">
						
							<h2><g:fieldValue bean="${infoInstance}" field="titulo"/></h2>
						
					</g:if>
				</div>

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>
								
					<g:if test="${infoInstance?.descripcion}">
							<markdown:renderHtml text="${infoInstance.descripcion}" />						
					</g:if>

			</div>

		</div>
	</body>
</html>